#!/bin/bash

set -o errexit

PROGDIR=/usr/local/tlscerts
source ${PROGDIR}/config.py
NEW_DIR=${TLSCERTS_VARDIR}/new

function cleanup {
	# Turn off errexit
	set +o errexit
	rm -fr ${NEW_DIR}/*
}
trap 'cleanup' EXIT

echo 'Generating new TLS certs...'

mkdir -p ${NEW_DIR}
chown 0:0 ${NEW_DIR}
chmod 700 ${NEW_DIR}

echo "${TLSCERTS_DOMAINS}" > ${NEW_DIR}/domains.txt

${PROGDIR}/letsencrypt.sh --cron --challenge dns-01 --force --config ${PROGDIR}/letsencrypt-config.sh

echo 'Success!'
