#!/bin/bash

set -e

source /usr/local/tlscerts/config.py

if ! openssl x509 -checkend $((TLSCERTS_RENEWALDAYS * 86400)) -noout -in ${TLSCERTS_VARDIR}/cert.pem; then
	/usr/local/tlscerts/gen-certs
fi
