#!/bin/bash

set -ex

# We don't need fullchain.pem, but installing it now prevents
# the cron job from reloading https by downloading it later,
# since it downloads everything in the s3 folder.
#
CERT_FILES="cert.pem privkey.pem chain.pem fullchain.pem"

source /usr/local/tlscerts/config.py

mkdir -p ${TLSCERTS_VARDIR}
chown root:${TLSCERTS_VARDIRGROUP} ${TLSCERTS_VARDIR}
chmod 550 ${TLSCERTS_VARDIR}

/usr/local/tlscerts/update-certs
